$(document).ready(function(){
    $("#btn-perros").click(function(){
        $("#btn-perros").addClass("btn-success");
        $(".perros").hide();
        $(".gato").hide();
        $(".pez").hide();
        $("#btn-peces").removeClass("btn-success");
        $("#btn-gatos").removeClass("btn-success");
        $("#btn-filtrar").removeClass("btn-success");   
    });
    $("#btn-gatos").click(function(){
        $("#btn-gatos").addClass("btn-success");
        $(".gato").show();
        $(".perro").hide();
        $(".pez").hide();   
        $("#btn-perros").removeClass("btn-success");
        $("#btn-peces").removeClass("btn-success");
        $("#btn-filtrar").removeClass("btn-success"); 
    });
    $("#btn-peces").click(function(){
        $("#btn-peces").addClass("btn-success");
        $(".pez").show();   
        $(".perro").hide();
        $(".gato").hide();   
        $("#btn-perros").removeClass("btn-success");
        $("#btn-gatos").removeClass("btn-success");
        $("#btn-filtrar").removeClass("btn-success"); 
    });
    $("#btn-filtrar").click(function(){
        $("#btn-peces").removeClass("btn-success");
        $("#btn-gatos").removeClass("btn-success");
        $("#btn-perros").removeClass("btn-success");
        $(".perro").show();
        $(".gato").show();   
        $(".pez").show();
    });
        
});
